In [1]:
#import some libraries
import os
import cv2
import numpy as np
import tensorflow as tf

## Using TensorFlow like Numpy
### A tensor is usally a multidimensonal array, but it can also hold a scalar (vô hướng) (a simple value, such as 42). These tensors will be important when we create custom cost functions, custom metrics, custom layers, ...

In [2]:
tf.constant([[1., 2., 3.], [4., 5., 6.]]) #Matrix  

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

**Notes**: These value above show us the shape of matrix with 2 rows and 3 columns (shape =(rows, columns)), and data types=float32 as well as the numpy version

In [4]:
#Indexing works much like in Numpy
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print(t[0, :]) #[1. 2. 3.]
print(t[:, 1:]) #[[2. 3.], [5. 6.]] (columns 1 and 2)


tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


**Notes**: We can see the difference betweem two shape of array. With the shape of (3,), it is a 1-ranked array not a dimensional array (e.g shape=(3,1))

In [5]:
# All sorts of tensor operations are available:
print(t + 10) #add 10 to each element
print(tf.square(t)) #square each element
print(tf.reduce_sum(t)) #sum all elements
print(tf.reduce_sum(t, 0)) #sum each column
print(tf.reduce_sum(t, 1)) #sum each row
print(tf.reduce_mean(t)) #mean of all elements
print(tf.reduce_mean(t, 0)) #mean of each column
print(tf.reduce_mean(t, 1)) #mean of each row
print(tf.transpose(t)) #swap rows and columns

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(21.0, shape=(), dtype=float32)
tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
tf.Tensor([ 6. 15.], shape=(2,), dtype=float32)
tf.Tensor(3.5, shape=(), dtype=float32)
tf.Tensor([2.5 3.5 4.5], shape=(3,), dtype=float32)
tf.Tensor([2. 5.], shape=(2,), dtype=float32)
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)


## Tensors and Numpy
### You can create a tensor from a NumPy array, and vice versa

In [6]:
a = np.array([2., 4., 5.])
print(tf.constant(a)) #[2. 4. 5.]
print(t.numpy()) #[1. 2. 3.]

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float64)
[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
print(tf.square(a)) #[4. 16. 25.]
print(np.square(t)) #[[1. 4. 9.], [16. 25. 36.]]

tf.Tensor([ 4. 16. 25.], shape=(3,), dtype=float64)
[[ 1.  4.  9.]
 [16. 25. 36.]]


**Warning**: Numpy uses 64-bit precision by default, while TensorFlow uses 32-bit precision (more than enough for neural networks, plus it faster and uses less RAM). So when we create a tensor from a NumPy array, make sure to set dtype=tf.float32

## Type conversions

In [8]:
# Using tf.cast() to convert between types
t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32) #42

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

## Variables
### The tf.Tensor values we have seen so far ar immutable (you can not modify them). This means that we cannot use regular tensors to implement weights in a neural network, since they need to be tweaked by backpropagation. That's why we need tf.Variable

In [9]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [10]:
"""
A Tf.Variable acts much like a tf.Tensor: you can perform the same operation with it, it plays nicely with NumPy as well.
But it can also be modified in place using tf.assign().
"""
v.assign(2 *  v)    # v is now [[2., 4., 6.], [8., 10., 12.]]
v[0,1].assign(42.)  # v is now [[2., 42., 6.], [8., 10., 12.]]
v[:, 2].assign([0., 1.])    # v is now [[2., 42., 0.], [8., 10., 1.]]
v.scatter_nd_update([[0, 0], [1, 2]], updates=[100., 200.]) # v is now [[100., 42., 0.], [8., 10., 200.]]

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>